[project]
name = "image_loopback"
description = ""
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/leocbehe/image_loopback"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pone"
DisplayName = "Image Loopback"
Icon = ""
